mutation createEmployee ($employeeData: EmployeeInput!) {
  createEmployee(data: $employeeData){
    _id
  }
}

mutation createSalary ($salaryData: SalaryInput!) {
  createSalary(data: $salaryData) {
    _id
  }
}

mutation partialUpdateEmployee($id: ID!, $employeeData: PartialUpdateEmployeeInput!){
  partialUpdateEmployee(id: $id, data: $employeeData){
    _id
  }
}