query activeEmployees {
  activeEmployees(active: true) {
    data {
      _id
      personal {
        firstName
        lastName
      }
      department{
        name
      }
      salaryHistory{
        data{
          position
        }
      }
    }
  }
}

query findEmployeeByID($id: ID!) {
  findEmployeeByID(id: $id) {
    _id
    personal {
      firstName
      middleName
      lastName
      address {
        number
        street
        city
        pobox
        code
        country
      }
      dateOfBirth
      telephone
      email
    }
    statutory {
      id
      pin
      nhif
      nssf
    }
    department {
      name
    }
    salary
    salaryHistory {
      data {
        date
        position
        allowances {
          name
          amount
        }
        basic
        gross
        active
      }
    }
    bank {
      accountName
      accountNumber
      bank
      bankCode
      branch
      branchCode
    }
    start
    leave
    loan
    active
  }
}
